server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stock-example
    username: root
    password: 1234
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/dvdrental
#    username: postgres
#    password: 1234
    hikari:
      maximum-pool-size: 40

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
